//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.11 at 07:38:49 PM CET 
//


package com.nikita.ws.soap.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nikita.ws.soap.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VerificationResult_QNAME = new QName("http://schema.soap.ws.nikita.com", "VerificationResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nikita.ws.soap.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VerificationResult }
     * 
     */
    public VerificationResult createVerificationResult() {
        return new VerificationResult();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VerificationResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.soap.ws.nikita.com", name = "VerificationResult")
    public JAXBElement<VerificationResult> createVerificationResult(VerificationResult value) {
        return new JAXBElement<VerificationResult>(_VerificationResult_QNAME, VerificationResult.class, null, value);
    }

}
