//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.11 at 07:38:49 PM CET 
//


package com.nikita.ws.soap.schema.operations;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nikita.ws.soap.schema.operations package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nikita.ws.soap.schema.operations
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CodeVerificationResponse }
     * 
     */
    public CodeVerificationResponse createCodeVerificationResponse() {
        return new CodeVerificationResponse();
    }

    /**
     * Create an instance of {@link CodeVerificationRequest }
     * 
     */
    public CodeVerificationRequest createCodeVerificationRequest() {
        return new CodeVerificationRequest();
    }

}
